// <auto-generated />
using System;
using Kithara.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kithara.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KitharaDbContext))]
    partial class KitharaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Kithara.Infrastructure.Persistence.Entities.QueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StrunaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TuneId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TuneId");

                    b.HasIndex("StrunaId", "Position")
                        .IsUnique();

                    b.ToTable("queue_entries", (string)null);
                });

            modelBuilder.Entity("Kithara.Infrastructure.Persistence.Entities.SearchResultCacheEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrincipalUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QueryKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalUserId", "ModuleSlug", "QueryKey");

                    b.ToTable("search_result_cache", (string)null);
                });

            modelBuilder.Entity("Kithara.Infrastructure.Persistence.Entities.Struna", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ControlAccess")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestCode")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ListenToken")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlaybackAccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("strunas", (string)null);
                });

            modelBuilder.Entity("Kithara.Infrastructure.Persistence.Entities.StrunaControlGrant", b =>
                {
                    b.Property<Guid>("StrunaId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("StrunaId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("struna_control_grants", (string)null);
                });

            modelBuilder.Entity("Kithara.Infrastructure.Persistence.Entities.Tune", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Artist")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArtworkUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationSeconds")
                        .HasColumnType("REAL");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModuleSlug", "ExternalId")
                        .IsUnique();

                    b.ToTable("tunes", (string)null);
                });

            modelBuilder.Entity("Kithara.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GuestStrunaId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ManagedByModuleSlug")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Kithara.Infrastructure.Persistence.Entities.UserAuthBinding", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSlug")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSubject")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "ProviderSlug");

                    b.ToTable("user_auth_bindings", (string)null);
                });

            modelBuilder.Entity("Kithara.Infrastructure.Persistence.Entities.QueueEntry", b =>
                {
                    b.HasOne("Kithara.Infrastructure.Persistence.Entities.Struna", "Struna")
                        .WithMany("QueueEntries")
                        .HasForeignKey("StrunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kithara.Infrastructure.Persistence.Entities.Tune", "Tune")
                        .WithMany("QueueEntries")
                        .HasForeignKey("TuneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Struna");

                    b.Navigation("Tune");
                });

            modelBuilder.Entity("Kithara.Infrastructure.Persistence.Entities.SearchResultCacheEntry", b =>
                {
                    b.HasOne("Kithara.Infrastructure.Persistence.Entities.User", "Principal")
                        .WithMany()
                        .HasForeignKey("PrincipalUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Principal");
                });

            modelBuilder.Entity("Kithara.Infrastructure.Persistence.Entities.Struna", b =>
                {
                    b.HasOne("Kithara.Infrastructure.Persistence.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Kithara.Infrastructure.Persistence.Entities.StrunaControlGrant", b =>
                {
                    b.HasOne("Kithara.Infrastructure.Persistence.Entities.Struna", "Struna")
                        .WithMany("ControlGrants")
                        .HasForeignKey("StrunaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kithara.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Struna");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kithara.Infrastructure.Persistence.Entities.Tune", b =>
                {
                    b.HasOne("Kithara.Infrastructure.Persistence.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("Kithara.Infrastructure.Persistence.Entities.UserAuthBinding", b =>
                {
                    b.HasOne("Kithara.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("AuthBindings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kithara.Infrastructure.Persistence.Entities.Struna", b =>
                {
                    b.Navigation("ControlGrants");

                    b.Navigation("QueueEntries");
                });

            modelBuilder.Entity("Kithara.Infrastructure.Persistence.Entities.Tune", b =>
                {
                    b.Navigation("QueueEntries");
                });

            modelBuilder.Entity("Kithara.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Navigation("AuthBindings");
                });
#pragma warning restore 612, 618
        }
    }
}
